---

- name: Ensure HAProxy is started and enabled on boot
  service:
    name: haproxy
    state: started
    enabled: yes
  tags:
  - service

- name: Ensure Keepalived is started and enabled on boot
  service:
    name: keepalived
    state: started
    enabled: yes
  when: haproxy_enable_ha|bool
  tags:
  - service
